version: '3.8'

services:
  frontend:
    container_name: react-vite-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
